const COMPOSITION_GRAPH = 'COMPOSITION_GRAPH';
const MISSION_GRAPH = 'MISSION_GRAPH';
const CAMPAIGNS = 'CAMPAIGNS';
const MAPPING = 'MAPPING';
const RESOURCE_NETWORK_GRAPH = 'RESOURCE_NETWORK_GRAPH';

type OptionType = typeof COMPOSITION_GRAPH | typeof MISSION_GRAPH | typeof CAMPAIGNS | typeof MAPPING | typeof RESOURCE_NETWORK_GRAPH;

export default OptionType;