enum OptionType {
    COMPOSITION_GRAPH = 'COMPOSITION_GRAPH',
    MISSION_GRAPH = 'MISSION_GRAPH',
    CAMPAIGNS = 'CAMPAIGNS',
    MAPPING = 'MAPPING',
    RESOURCE_NETWORK_GRAPH = 'RESOURCE_NETWORK_GRAPH',
}
export default OptionType;