enum ViewType {
    HOME = 'HOME',
    LOGIN = 'LOGIN',
    OUTPUT = 'OUTPUT',
    SETTINGS = 'SETTINGS',
    COMPOSITION = 'COMPOSITION',
    MISSION = 'MISSION',
    MAPPING = 'MAPPING',
    RESOURCE_NETWORK = 'RESOURCE_NETWORK',
    DYREQT_RUN = 'DYREQT_RUN',
}
export default ViewType;